import Head from 'next/head'
import EventList from '../components/events/EventList'
import { getFeaturedEvents } from '../data/DUMMY_DATA'


export default function Home() {
  const featuredEvents = getFeaturedEvents();
  return (
    <div>
      <Head>
        <title>blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <EventList items={featuredEvents} />
        </div>
      </main>

     </div>
  )
}
